### ISSUE TITLE
HP Gen 8/9

### ISSUE THREAD

**Issue by BShurilla** [BShurilla/homelablabelmaker#2]
HP Gen 8/9

https://imgur.com/a/Pr9Ux80/ 

https://www.reddit.com/user/TillyFace89

**Comment by nerdalertdk** [comment]
Thats an IBM server :)

**Comment by BShurilla** [comment]
Completed by  NickWaterton, thanks so much! I will get this updated on the web real quick.

**Comment by BShurilla** [comment]
updates are live
